config/routes.rb
PresCaenCamp::Application.routes.draw do
  resources :commentaires do
    collection do
      put 'valide_commentaire'
      get 'liste_commentaires_actifs_pseudo'
    end
  end

end

app/models/commentaire.rb
class Commentaire < ActiveRecord::Base
  attr_accessible :actif, :contenu, :pseudo

  def valider
    self.actif = true
    save
  end

  def refuser
    self.actif = false
    save
  end

  class << self
    def liste_commentaires_pseudo(pseudo)
      return Commentaire.all(:conditions => {:pseudo => pseudo})
    end

    def liste_commentaires_actifs_pseudo(pseudo)
      return liste_commentaires_pseudo(pseudo).select { |c| c.actif }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/commentaires_controller.rb
class CommentairesController < ApplicationController
  def liste_commentaires_actifs_pseudo
    @commentaires = Commentaire.liste_commentaires_actifs_pseudo(params[:pseudo])
    #render :nothing => true
    respond_to do |format|
      format.html { render :nothing => true }
      format.json { render :json => @commentaires }
    end
  end

  def valide_commentaire
    commentaire = Commentaire.find(params[:id])
    commentaire.valider
    respond_to do |format|
      format.html { redirect_to :action => "index" }
      format.json { render :json => commentaire }
    end
  end

  # GET /commentaires
  # GET /commentaires.json
  def index
    @commentaires = Commentaire.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @commentaires }
    end
  end

  # GET /commentaires/1
  # GET /commentaires/1.json
  def show
    @commentaire = Commentaire.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @commentaire }
    end
  end

  # GET /commentaires/new
  # GET /commentaires/new.json
  def new
    @commentaire = Commentaire.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @commentaire }
    end
  end

  # GET /commentaires/1/edit
  def edit
    @commentaire = Commentaire.find(params[:id])
  end

  # POST /commentaires
  # POST /commentaires.json
  def create
    @commentaire = Commentaire.new(params[:commentaire])

    respond_to do |format|
      if @commentaire.save
        format.html { redirect_to @commentaire, :notice => 'Commentaire was successfully created.' }
        format.json { render :json => @commentaire, :status => :created, :location => @commentaire }
      else
        format.html { render :action => "new" }
        format.json { render :json => @commentaire.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /commentaires/1
  # PUT /commentaires/1.json
  def update
    @commentaire = Commentaire.find(params[:id])

    respond_to do |format|
      if @commentaire.update_attributes(params[:commentaire])
        format.html { redirect_to @commentaire, :notice => 'Commentaire was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @commentaire.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /commentaires/1
  # DELETE /commentaires/1.json
  def destroy
    @commentaire = Commentaire.find(params[:id])
    @commentaire.destroy

    respond_to do |format|
      format.html { redirect_to commentaires_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commentaires_helper.rb
module CommentairesHelper
end

app/views/commentaires/_form.html.erb
<%= form_for(@commentaire) do |f| %>
  <% if @commentaire.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commentaire.errors.count, "error") %> prohibited this commentaire from being saved:</h2>

      <ul>
      <% @commentaire.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pseudo %><br />
    <%= f.text_field :pseudo %>
  </div>
  <div class="field">
    <%= f.label :contenu %><br />
    <%= f.text_area :contenu %>
  </div>
  <div class="field">
    <%= f.label :actif %><br />
    <%= f.check_box :actif %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/commentaires/edit.html.erb
<h1>Editing commentaire</h1>

<%= render 'form' %>

<%= link_to 'Show', @commentaire %> |
<%= link_to 'Back', commentaires_path %>

app/views/commentaires/index.html.erb
<h1>Listing commentaires</h1>

<table>
  <tr>
    <th>Pseudo</th>
    <th>Contenu</th>
    <th>Actif</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @commentaires.each do |commentaire| %>
  <tr>
    <td><%= commentaire.pseudo %></td>
    <td><%= commentaire.contenu %></td>
    <td><%= commentaire.actif %></td>
    <td><%= link_to 'Show', commentaire %></td>
    <td><%= link_to 'Edit', edit_commentaire_path(commentaire) %></td>
    <td><%= link_to 'Destroy', commentaire, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Commentaire', new_commentaire_path %>

app/views/commentaires/new.html.erb
<h1>New commentaire</h1>

<%= render 'form' %>

<%= link_to 'Back', commentaires_path %>

app/views/commentaires/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Pseudo:</b>
  <%= @commentaire.pseudo %>
</p>

<p>
  <b>Contenu:</b>
  <%= @commentaire.contenu %>
</p>

<p>
  <b>Actif:</b>
  <%= @commentaire.actif %>
</p>


<%= link_to 'Edit', edit_commentaire_path(@commentaire) %> |
<%= link_to 'Back', commentaires_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PresCaenCamp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>